Credits scene
Blamcho/where-is-my-wife pull request #28
Opened 2024-10-24 05:23 UTC by PaTo81013

2024-10-24 15:46 UTC, Horothenic requested changes
Rejected from video

2024-10-25 20:20 UTC, PaTo81013 commented
[https://youtube.com/live/JWySrw_oIok](url)

2024-10-25 20:21 UTC, PaTo81013 commented
(https://youtube.com/live/JWySrw_oIok)

2024-10-25 21:22 UTC, Horothenic requested changes

2024-10-25 21:22 UTC, Horothenic commented on Where_Is_My_Wife/Assets/_Main/Scripts/UI/Credits/Credits.cs
> +
Remove this extra space

2024-10-25 21:22 UTC, Horothenic commented on Where_Is_My_Wife/Assets/_Main/Scripts/UI/Credits/Credits.cs
> +
Remove this extra space

2024-10-25 21:22 UTC, Horothenic commented on Where_Is_My_Wife/Assets/_Main/Scripts/UI/Credits/Credits.cs
> +public class Credits : MonoBehaviour
Encapsulate this class in `namespace WhereIsMyWife.UI`

2024-10-25 22:17 UTC, Horothenic approved these changes

2024-10-25 22:17 UTC, merged